security:
    encoders:
        # j'ai hashé mes mots de passe avec la commande
        # symfony console security:encode-password 'your_plain_password' 'App\Entity\YourUserClass'
        # puis écrire "encoded password" dans la base de données

        App\Entity\User:
            algorithm: auto
 # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
         # used to reload user from session & other features (e.g. switch_user)
        app_user_provider: 
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:

            anonymous: lazy
            provider: users_in_memory

            guard:

                authenticators:
                    - App\Security\LoginFormAuthenticationAuthenticator
                entry_point: App\Security\LoginFormAuthenticationAuthenticator

            logout:
                path: app_logout
                # where to redirect after logout
                target: /login
    access_control:
        #les étudiants n'a pas l'accées aux analyses et les enseignants n'ont pas l'autorisation de répondre aux enquètes
        - { path: ^/anneescolaire/*, roles: ROLE_ADMIN}
        - { path: ^/qcmlist/*, roles: ROLE_USER}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
